### ISSUE TITLE
马甲包

### ISSUE THREAD

**Issue by SamuelZon258** [xerysherry/CSharp_Garbage_Code_Generater#1]
这个生成400多个文件够用么？ Native文件夹有8000多个脚本 就400个不同貌似用处不大吧

**Comment by xerysherry** [comment]
400个垃圾文件，我们这边现在就是这样过了不少马甲包。
其实8000文件里有不少系统代码，真正我们开发相关的代码真的不多哦。

**Comment by SamuelZon258** [comment]
谢谢回答 不过我们弄了2000个上去试试先 安全点 最近急着上包

**Comment by SamuelZon258** [comment]
貌似加了2000个垃圾类还是被拒 怀疑现在是不是改策略了

**Comment by xerysherry** [comment]
被拒很正常，垃圾代码只能保证尽量不被机器之间筛查出来。
之后到人工阶段还是看人品了。

**Comment by huangwenxian** [comment]
@ZonSamuel   你试了多少个包？都是被拒吗？

**Comment by QQ53792889** [comment]
@ZonSamuel 有APP开发和上架苹果商店的技术吗？单个5W有意私聊
@xerysherry
