### ISSUE TITLE
生成的命名都是随机的字符串，没有意义，能改成有意义的单词拼接而成吗？

### ISSUE THREAD

**Issue by huangwenxian** [xerysherry/CSharp_Garbage_Code_Generater#3]
<img width="601" alt="1a77e077-0752-4f42-981c-3307e836bfdf" src="https://user-images.githubusercontent.com/14084677/48049924-3babc380-e1db-11e8-9efa-015966b1f3c0.png">

**Comment by xerysherry** [comment]
本来就是垃圾代码，用有意义的单词，意义何在？

**Comment by huangwenxian** [comment]
这样会被苹果认为故意混淆。我自己已经改好了。谢谢你的脚本啦
